parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint/eslint-plugin"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
root: true
env:
  node: true
  jest: true
ignorePatterns:
  - ".eslintrc.js"
  - "**/*.js"
  - "**/*.test.ts"
rules:
  "@typescript-eslint/interface-name-prefix": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-empty-function": "off"
  "comma-dangle": 0
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/no-unused-vars": 1
  # "key-spacing":
  #   - "error"
  #   - align:
  #       beforeColon: true
  #       afterColon: true
  #       on: "colon"
