aws_profile: qnect
app: backend
region: ap-northeast-2
useAWSSDKV3: true
claimsProfiles:
  user_email: spark-test@rubywave.io
  client_id: testclient
  provider: "api-key"
env:
  stage: dev
  version: 1
  service: qnect
  dsql_endpoint: 2qabuf7be24l74wozitfemo2xi.dsql.ap-northeast-2.on.aws
  region: ap-northeast-2

  
  # - uri: template/get.js
  #   eventType: http
  #   description: emplate get2
  #   method: get
  #   params:
  #     pk: test
  #     sk: sk
  #   expect:
  #     checkType: check_200
