aws_profile: admin_rubywave_lecture_sandbox
app: demo-http
region: ap-northeast-2
env:
  counter_table_name: Demo-Counter-dev-1


test_targets:
  - uri: counter/put.js
    eventType: http
    description: put
    method: put
    parms:
      counterId: mycounter
      value: 2
    expect:
      checkType: check_200
